use std::fs;

use tempfile::tempdir;
use unifier::core::evidence::{ExpressionKind, SymbolKind, TextRole};
use unifier::core::frontend::extract_text_evidence;
use unifier::core::scanner::scan_workspace;

#[test]
fn c_family_generated_amalgamation_file_is_marked_generated() {
    let dir = tempdir().unwrap();
    let file = dir.path().join("jimsh0.c");
    fs::write(
        &file,
        r#"
/* This is single source file, bootstrap version of Jim Tcl */
#define JIM_VERSION 81
#define JIM_COMPAT 1
typedef struct Jim_Obj Jim_Obj;
"#,
    )
    .unwrap();

    let state = scan_workspace(dir.path(), &[]).unwrap();
    let store = extract_text_evidence(&state).unwrap();
    let unit = store
        .file_units
        .iter()
        .find(|unit| unit.path.ends_with("jimsh0.c"))
        .expect("generated C file is scanned");

    assert!(
        unit.generated,
        "bootstrap single-source files must be marked generated"
    );
}

#[test]
fn non_c_family_generated_marker_headers_are_not_marked_generated() {
    let dir = tempdir().unwrap();
    fs::write(
        dir.path().join("generated_marker.py"),
        "# generated by fixture\ndef run():\n    return 1\n",
    )
    .unwrap();
    fs::write(
        dir.path().join("generated_marker.rs"),
        "// generated by fixture\nfn run() -> i32 { 1 }\n",
    )
    .unwrap();

    let state = scan_workspace(dir.path(), &[]).unwrap();
    let store = extract_text_evidence(&state).unwrap();

    for path in ["generated_marker.py", "generated_marker.rs"] {
        let unit = store
            .file_units
            .iter()
            .find(|unit| unit.path.ends_with(path))
            .expect("file is scanned");
        assert!(
            !unit.generated,
            "{path} must not be marked generated by Task 6 C/C++ marker policy"
        );
    }
}

#[test]
fn c_family_non_utf8_generated_marker_bytes_are_not_marked_generated() {
    let dir = tempdir().unwrap();
    let file = dir.path().join("invalid_marker.c");
    let mut bytes = b"/* do not edit */\nint run(void);\n".to_vec();
    bytes.insert(0, 0xff);
    fs::write(&file, bytes).unwrap();

    let state = scan_workspace(dir.path(), &[]).unwrap();
    let store = extract_text_evidence(&state).unwrap();
    let unit = store
        .file_units
        .iter()
        .find(|unit| unit.path.ends_with("invalid_marker.c"))
        .expect("non-UTF8 C file is scanned");

    assert!(
        !unit.generated,
        "non-UTF8 generated-marker bytes must be treated as an empty header"
    );
}

#[test]
fn c_family_generated_marker_after_forty_lines_is_marked_generated() {
    let dir = tempdir().unwrap();
    let file = dir.path().join("generated_header.c");
    let mut source = String::new();
    for index in 0..45 {
        source.push_str(&format!("// filler line {index}\n"));
    }
    source.push_str("// generated by fixture\nint run(void);\n");
    assert!(source.len() < 8192);
    fs::write(&file, source).unwrap();

    let state = scan_workspace(dir.path(), &[]).unwrap();
    let store = extract_text_evidence(&state).unwrap();
    let unit = store
        .file_units
        .iter()
        .find(|unit| unit.path.ends_with("generated_header.c"))
        .expect("generated C file is scanned");

    assert!(
        unit.generated,
        "generated markers inside the 8192-byte header must not be limited to the first 40 lines"
    );
}

#[test]
fn c_family_generated_marker_after_header_limit_is_not_marked_generated() {
    let dir = tempdir().unwrap();
    let file = dir.path().join("late_marker.c");
    let mut source = " ".repeat(8192);
    source.push_str("// generated by fixture\nint run(void);\n");
    assert!(source.find("generated by").unwrap() >= 8192);
    fs::write(&file, source).unwrap();

    let state = scan_workspace(dir.path(), &[]).unwrap();
    let store = extract_text_evidence(&state).unwrap();
    let unit = store
        .file_units
        .iter()
        .find(|unit| unit.path.ends_with("late_marker.c"))
        .expect("C file is scanned");

    assert!(
        !unit.generated,
        "generated markers starting after the 8192-byte header must not be detected"
    );
}

#[test]
fn c_family_macros_are_symbols_but_not_public_doc_surfaces() {
    let dir = tempdir().unwrap();
    let file = dir.path().join("feature_flags.h");
    fs::write(
        &file,
        r#"
#ifndef FEATURE_FLAGS_H
#define FEATURE_FLAGS_H
#define FEATURE_ENABLED 1
#endif
"#,
    )
    .unwrap();

    let state = scan_workspace(dir.path(), &[]).unwrap();
    let store = extract_text_evidence(&state).unwrap();

    assert!(
        store
            .symbols
            .iter()
            .any(|symbol| symbol.name == "FEATURE_ENABLED" && symbol.kind == SymbolKind::Macro),
        "macro symbol is still extracted for Cpp006 and Cpp010"
    );

    assert!(
        store
            .public_surfaces
            .iter()
            .all(|surface| surface.symbol_name != "FEATURE_ENABLED"),
        "macro symbols must not enter Core011 public-doc surface facts"
    );
}

#[test]
fn extracts_cpp_doc_for_symbol_and_skips_call_site_symbols() {
    let dir = tempdir().unwrap();
    fs::write(
        dir.path().join("api.cpp"),
        "/** 运行 */\n\
int run(int value) {\n\
    helper();\n\
    return helper(value);\n\
}\n\
int second(void) { return 0; }\n",
    )
    .unwrap();
    let state = scan_workspace(dir.path(), &[]).unwrap();
    let store = extract_text_evidence(&state).unwrap();

    assert!(store
        .text_spans
        .iter()
        .any(|text| text.role == TextRole::DocSummary && text.normalized_text == "运行"));
    assert!(store
        .symbols
        .iter()
        .any(|symbol| symbol.name == "run" && symbol.doc_region_id.is_some()));
    assert!(!store.symbols.iter().any(|symbol| symbol.name == "helper"));
    assert!(store
        .symbols
        .iter()
        .any(|symbol| symbol.name == "second" && symbol.doc_region_id.is_none()));
}

#[test]
fn extracts_c_and_cpp_include_header_and_macro_facts() {
    let dir = tempdir().unwrap();
    fs::write(
        dir.path().join("api.hpp"),
        "#ifndef API_HPP\n\
#define API_HPP\n\
#include <vector>\n\
using namespace std;\n\
#define CALL(x) ((x) + (x))\n\
template <typename T>\n\
T convert(T value);\n\
#if defined(DEBUG)\n\
int* value = new int;\n\
#endif\n\
extern \"C\" int run(int* value);\n\
#endif\n",
    )
    .unwrap();
    let state = scan_workspace(dir.path(), &[]).unwrap();
    let store = extract_text_evidence(&state).unwrap();

    assert!(store
        .module_units
        .iter()
        .any(|module| module.is_header && module.include_guard.as_deref() == Some("API_HPP")));
    assert!(store
        .dependency_edges
        .iter()
        .any(|edge| edge.source == "vector"));
    assert!(store
        .symbols
        .iter()
        .any(|symbol| symbol.name == "CALL" && symbol.kind == SymbolKind::Macro));
    assert!(store
        .dependency_edges
        .iter()
        .any(|edge| edge.source == "std" && edge.imported == "*" && edge.is_glob));
    assert!(store
        .symbols
        .iter()
        .any(|symbol| symbol.name == "convert"
            && symbol.attributes.contains(&"template".to_string())));
    assert!(store
        .block_regions
        .iter()
        .any(|block| block.kind == "preprocessor"));
    assert!(store
        .expressions
        .iter()
        .any(|expr| expr.kind == ExpressionKind::Allocation));
    assert!(store.symbols.iter().any(|symbol| symbol.name == "run"));
}

#[test]
fn c_allocation_facts_ignore_strings_and_similar_function_names() {
    let dir = tempdir().unwrap();
    fs::write(
        dir.path().join("api.c"),
        "void jim_regfree(regex_t *preg); /* mention new object */\n\
/* Allocate and return a new object */\n\
** Link the new scan object\n\
const char *script = \"file delete force\";\n\
void run(void) {\n\
    free(ptr);\n\
    int *value = new int;\n\
}\n",
    )
    .unwrap();
    let state = scan_workspace(dir.path(), &[]).unwrap();
    let store = extract_text_evidence(&state).unwrap();
    let allocations = store
        .expressions
        .iter()
        .filter(|expr| expr.kind == ExpressionKind::Allocation)
        .collect::<Vec<_>>();

    assert_eq!(allocations.len(), 2);
    assert!(allocations
        .iter()
        .any(|expr| expr.text.contains("free(ptr)")));
    assert!(allocations.iter().any(|expr| expr.text.contains("new int")));
    assert!(!allocations.iter().any(|expr| expr.text.contains("regfree")
        || expr.text.contains("delete force")
        || expr.text.contains("new object")
        || expr.text.contains("new scan")));
}
